import { FaFilePdf, FaGithub, FaInstagram, FaLinkedinIn, FaWhatsapp } from "react-icons/fa6"
import {
  LuArrowRight,
  LuBell,
  LuBlocks,
  LuBriefcase,
  LuChartColumnBig,
  LuCircleCheckBig,
  LuCircleX,
  LuFileCode2,
  LuFileUser,
  LuGlobe,
  LuKeyRound,
  LuLayoutDashboard,
  LuLayoutTemplate,
  LuListTodo,
  LuMail,
  LuMenu,
  LuMessageSquareText,
  LuPalette,
  LuPaperclip,
  LuQuote,
  LuSearch,
  LuShield,
  LuShieldCheck,
  LuSparkles,
  LuUserRound,
  LuX,
} from "react-icons/lu"
import {
  SiCss,
  SiExpress,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiNodedotjs,
  SiReact,
  SiRender,
  SiSocketdotio,
  SiVercel,
  SiVite,
} from "react-icons/si"

const icons = {
  dashboard: LuLayoutDashboard,
  tasks: LuListTodo,
  services: LuBriefcase,
  messages: LuMessageSquareText,
  profile: LuUserRound,
  admin: LuShield,
  analytics: LuChartColumnBig,
  resume: LuFileUser,
  notification: LuBell,
  search: LuSearch,
  quote: LuQuote,
  attachment: LuPaperclip,
  sparkle: LuSparkles,
  approved: LuCircleCheckBig,
  rejected: LuCircleX,
  arrow: LuArrowRight,
  menu: LuMenu,
  close: LuX,
  github: FaGithub,
  mail: LuMail,
  linkedin: FaLinkedinIn,
  instagram: FaInstagram,
  whatsapp: FaWhatsapp,
  react: SiReact,
  vite: SiVite,
  javascript: SiJavascript,
  html: SiHtml5,
  css: SiCss,
  nodejs: SiNodedotjs,
  express: SiExpress,
  mongodb: SiMongodb,
  jwt: LuKeyRound,
  oauth: LuShieldCheck,
  socketio: SiSocketdotio,
  git: SiGit,
  vercel: SiVercel,
  render: SiRender,
  pdf: FaFilePdf,
  api: LuFileCode2,
  responsive: LuLayoutTemplate,
  components: LuBlocks,
  uxui: LuPalette,
  crud: LuFileCode2,
  seo: LuGlobe,
  saas: LuLayoutDashboard,
}

export default function IconSymbol({ name, className = "" }) {
  const Icon = icons[name] || icons.dashboard
  return <Icon aria-hidden="true" className={className} focusable="false" />
}
